layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # twitter: ale_martinello
  linkedin: alessandro-martinello-a2766823
  bluesky: alemartinello.com
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

pinned-projects:
  - name: "Long-run saving dynamics: Evidence from unexpected inheritances"
    web_url: https://github.com/alemartinello/long-run-saving-dynamics
    image_url: https://raw.githubusercontent.com/alemartinello/long-run-saving-dynamics/master/paper/pic.png

  - name: "Placement optimization in refugee resettlement"
    web_url: https://swopec.hhs.se/lunewp/abs/lunewp2018_023.htm
    image_url: https://raw.githubusercontent.com/alemartinello/Papers/master/annie-moore/pic.png

  - name: "Substantial transmission of SARS-CoV-2 through casual contact in retail stores: Evidence from matched administrative microdata on card payments and testing"
    web_url: https://www.pnas.org/doi/10.1073/pnas.2317589121
    image_url: https://www.pnas.org/cms/10.1073/pnas.2317589121/asset/2d912c70-696f-478b-8e2e-e2a59963fa16/assets/images/large/pnas.2317589121fig05.jpg

markdown: kramdown