layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  twitter: ale_martinello
  linkedin: alessandro-martinello-a2766823
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

pinned-projects:
  - name: "Long-run saving dynamics: Evidence from unexpected inheritances"
    web_url: https://raw.githubusercontent.com/alemartinello/Papers/master/long-run-saving-dynamics/paper.pdf
    image_url: https://raw.githubusercontent.com/alemartinello/Papers/master/long-run-saving-dynamics/pic.png

  - name: Project 2

  - name: Project 3
