project:
  type: website
  resources:
  - files/*

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: About
      - tidbits.qmd
      - research.qmd
    tools:
      - icon: linkedin
        href: https://dk.linkedin.com/in/alessandro-martinello-a2766823
      - icon: github
        href: https://github.com/alemartinello
      # - icon: '{{< iconify simple-icons:bluesky >}}'
      #   href: https://bsky.app/profile/alemartinello.com
format:
  html:
    theme: lux
    css: styles.css
    toc: true



